MVC-09-09-16/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_09_09_16.Models
{
    [Table("person", Schema = "adm")]
    public class Person
    {
        [Key]
        public int Id { get; set; }

        [Index("INDEX_ADM_PERSON", 1, IsUnique = true)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar el nombre")]
        [StringLength(30, ErrorMessage = "El nombre no debe ser mayor de 30 caracteres.")]
        [Display(Name = "Nombre")]
        public string Name { get; set; }

        [Index("INDEX_ADM_PERSON", 2, IsUnique = true)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar el apellido")]
        [StringLength(30, ErrorMessage = "El apellido no debe ser mayor de 30 caracteres.")]
        [Display(Name = "Apellido")]
        public string LastName { get; set; }

        public int TypeIdentificationId { get; set; }

        [Index("INDEX_ADM_PERSON_IDENTIFICATION", IsUnique = true)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Debe ingresar el numero de identificacion")]
        [StringLength(20, ErrorMessage = "La identificacion no debe ser mayor de 20 caracteres.")]
        [Display(Name = "Identificacion")]
        public string Identification { get; set; }

        public bool Active { get; set; }

        public virtual TypeIdentification TypeIdentifications { get; set; }
    }
}

MVC-09-09-16/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_09_09_16.Models;
using PagedList;

namespace MVC_09_09_16.Controllers
{
    public class PersonsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index2()
        {
            ViewBag.TypeIdentificationId = new SelectList(db.TypeIdentifications.OrderBy(p => p.Name), "Id", "Name");
            return View();
        }

        public JsonResult getPerson()
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<Person> people = db.Persons.ToList();
            return Json(people, JsonRequestBehavior.AllowGet);
        }
        // GET: Personas
        public ActionResult Index(string sort ,string search, int? page)
        {
            ViewBag.NameSort = sort == "Name" ? "Name_desc" : "Name";
            ViewBag.LastNameSort = sort == "LastName" ? "LastName_desc" : "LastName";
            ViewBag.TypeIdentificationSort = sort == "TypeIdentification" ? "TypeIdentification_desc" : "TypeIdentification";
            ViewBag.IdentificationSort = sort == "Identification" ? "Identification_desc" : "Identification";

            ViewBag.CurrentSort = sort;
            ViewBag.CurrentSearch = search;

            IQueryable<Person> personae = db.Persons;

            if (!String.IsNullOrEmpty(search))
                personae = personae.Where(pp => pp.Name.Contains(search) || pp.Identification.Contains(search) || pp.TypeIdentifications.Name.Contains(search));
            switch (sort)
            {
                case "Name":
                    personae = personae.OrderBy(p => p.Name).ThenBy(p => p.LastName);
                    break;
                case "Name_desc":
                    personae = personae.OrderByDescending(p => p.Name);
                    break;
                case "LastName":
                    personae = personae.OrderBy(p => p.LastName);
                    break;
                case "LastName_desc":
                    personae = personae.OrderByDescending(p => p.LastName);
                    break;
                case "TypeIdentification":
                    personae = personae.OrderBy(p => p.TypeIdentifications.Name);
                    break;
                case "TypeIdentification_desc":
                    personae = personae.OrderByDescending(p => p.TypeIdentifications.Name);
                    break;
                case "Identification":
                    personae = personae.OrderBy(p => p.Identification);
                    break;
                case "Identification_desc":
                    personae = personae.OrderByDescending(p => p.Identification);
                    break;
                default:
                    personae = personae.OrderBy(p => p.Name);
                    break;
            }

            int pageSize = 3;
            int pageNumber = page ?? 1;
            return View(personae.ToPagedList(pageNumber, pageSize));
        }

        // GET: Personas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person persona = await db.Persons.FindAsync(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // GET: Personas/Create
        public ActionResult Create()
        {
            ViewBag.TypeIdentificationId = new SelectList(db.TypeIdentifications.OrderBy(p => p.Name), "Id", "Name");
            return View();
        }

        // POST: Personas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,LastName,TypeIdentificationId,Identification,Active")] Person person)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Persons.Add(person);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    var e = ex.GetBaseException() as SqlException;
                    if (e != null)
                        switch (e.Number)
                        {
                            case 2601:
                                TempData["MessageToClient"] = String.Format("DATOS DUPLICADOS DEL REGISTRO A GUARDAR!");
                                break;
                            default:
                                throw;
                        }
                }
            }

            return View(person);
        }

        // GET: Personas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person persona = await db.Persons.FindAsync(id);

            ViewBag.TypeIdentificationId = new SelectList(db.TypeIdentifications.OrderBy(p => p.Name), "Id", "Name", persona.TypeIdentificationId);

            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,LastName,TypeIdentificationId,Identification")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: Personas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person persona = await db.Persons.FindAsync(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Person persona = await db.Persons.FindAsync(id);
            db.Persons.Remove(persona);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC-09-09-16/Views/Persons/Create.cshtml
@model MVC_09_09_16.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        <h4><p class="text-danger">@TempData["MessageToClient"]</p></h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        @*<div class="form-group">
            @Html.LabelFor(model => model.TypeIdentificationId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeIdentificationId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeIdentificationId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.TypeIdentifications.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeIdentificationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeIdentificationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Identification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Identification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Identification, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC-09-09-16/Views/Persons/Delete.cshtml
@model MVC_09_09_16.Models.Person

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Identification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identification)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC-09-09-16/Views/Persons/Details.cshtml
@model MVC_09_09_16.Models.Person

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Identification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identification)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC-09-09-16/Views/Persons/Edit.cshtml
@model MVC_09_09_16.Models.Person

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.TypeIdentifications.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeIdentificationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeIdentificationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Identification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Identification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Identification, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC-09-09-16/Views/Persons/Index.cshtml
@using MVC_09_09_16.Models
@using PagedList.Mvc
@model PagedList.IPagedList<MVC_09_09_16.Models.Person>

<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "Lista de personas";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Persons", FormMethod.Get, new {@class = "form-inline"}))
{
    @Html.Label("search","Nombre o Identificacion: ", new {@class = "control-label"})
    @Html.TextBox("search",ViewBag.CurrentSearch as string, new {@class = "form-control"})
    <input type="submit" value="Buscar" class="btn btn-default"/>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Nombre)*@
            @Html.ActionLink("Nombre", "Index", new { sort = ViewBag.NameSort, search = ViewBag.CurrentSearch })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Apellido)*@
            @Html.ActionLink("Apellido", "Index", new { sort = ViewBag.LastNameSort, search = ViewBag.CurrentSearch })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Identificacion)*@
            @Html.ActionLink("Tipo de identificacion", "Index", new { sort = ViewBag.TypeIdentificationSort, search = ViewBag.CurrentSearch })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Identificacion)*@
            @Html.ActionLink("Identificacion", "Index", new { sort = ViewBag.IdentificationSort, search = ViewBag.CurrentSearch })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeIdentifications.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Identification)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new {page, sort = ViewBag.CurrentSort, search = ViewBag.CurrentSearch}))

MVC-09-09-16/Views/Persons/Index2.cshtml
@model MVC_09_09_16.Models.Person

@{
    ViewBag.Title = "Registro de personas";
}

<h2>@ViewBag.Title</h2>

<table class="table" id="dinamicTable">
    <thead>
        <tr><th><a id="agregar" href="#" type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalAgregar">Agregar</a></th></tr>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Tipo de identificacion</th>
            <th>Identificacion</th>
        </tr>
    </thead>
    <tbody>
        
    </tbody>
</table>


@*Ventana modal para agregar un nuevo registro*@
<div id="modalAgregar" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Añadir un nuevo registro</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "Persons", FormMethod.Post, new { id = "formPersons" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Persona</h4>
                        <hr />
                        <h4><p class="text-danger">@TempData["MessageToClient"]</p></h4>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-offset-1 col-md-9">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @*<input type="text" class="form-control" id="name" name="name">*@
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-offset-1 col-md-9">
                                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                @*<input type="text" class="form-control" id="lastname" name="lastname">*@
                                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.TypeIdentifications.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-offset-1 col-md-9">
                                @Html.DropDownList("TypeIdentificationId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TypeIdentificationId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Identification, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-offset-1 col-md-9">
                                @Html.EditorFor(model => model.Identification, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Identification, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-offset-1 col-md-9">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Active)
                                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9">
                                <input id="sendData" type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@*Ventana Modal para confirmacion de eliminar un registro*@
<div id="modalEliminar" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Eliminar un registro</h4>
            </div>
            <div class="modal-body">
                <h3>Are you sure you want to delete this?</h3>
                <div>
                    <h4>Persona</h4>
                    <hr />
                    

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input id="deletePerson" type="submit" value="Delete" class="btn btn-default" /> |
                            @Html.ActionLink("Back to List", "Index2")
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@*Ventana modal de editar*@
<div id="modalEditar" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Editar un registro</h4>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formEditar" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Persona</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.TypeIdentifications.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("TypeIdentificationId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.TypeIdentificationId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Identification, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Identification, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Identification, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input id="btnActualizar" type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>